/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        background: '#f8fafc',
        surface: '#ffffff',
        'ivory-surface': '#f8fafc',
        'surface-container': '#f1f5f9',
        'surface-container-low': '#f8fafc',
        'surface-container-high': '#e2e8f0',
        'on-surface': '#0f172a',
        'on-surface-variant': '#334155',
        outline: '#64748b',
        'outline-variant': '#cbd5e1',
        primary: '#162035',
        'on-primary': '#ffffff',
        'primary-container': '#1e2c4a',
        'on-primary-container': '#cbd5e1',
        'primary-fixed': '#dbeafe',
        'primary-fixed-dim': '#93c5fd',
        secondary: '#8a6d2b',
        'secondary-container': '#fef3c7',
        'secondary-fixed': '#fde68a',
        'secondary-fixed-dim': '#fcd34d',
        'tertiary-fixed': '#e2e8f0',
        'gold-shimmer': '#d4af37',
        'gold-accent': '#c59b27',
        'silver-accent': '#e2e8f0',
        'deep-navy': '#0f172a',
        'royal-slate': '#162035',
      },
      spacing: {
        'container-max': '1280px',
        'section-padding-desktop': '120px',
        'section-padding-mobile': '64px',
        gutter: '32px',
      },
      fontFamily: {
        display: ['var(--font-bodoni)', 'serif'],
        body: ['var(--font-opensans)', 'sans-serif'],
      },
      fontSize: {
        'display-lg': ['clamp(38px,6.5vw,64px)', { lineHeight: '1.1', letterSpacing: '-0.02em', fontWeight: '600' }],
        'headline-lg': ['clamp(30px,4.5vw,48px)', { lineHeight: '1.16', fontWeight: '500' }],
        'headline-md': ['32px', { lineHeight: '40px', fontWeight: '500' }],
        'title-lg': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'label-md': ['14px', { lineHeight: '20px', letterSpacing: '0.05em', fontWeight: '600' }],
      },
    },
  },
  plugins: [],
};
