/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        background: '#fbfcfd',
        surface: '#ffffff',
        'ivory-surface': '#f8fafd',
        'surface-container': '#f0f4fa',
        'surface-container-low': '#f8fafd',
        'surface-container-high': '#e2ebf6',
        'on-surface': '#0b162c',
        'on-surface-variant': '#30425e',
        outline: '#687d9c',
        'outline-variant': '#cbd8e8',
        // Diamor Royal Blue (from official logo #003190)
        primary: '#003190',
        'on-primary': '#ffffff',
        'primary-container': '#002268',
        'on-primary-container': '#d6e3f8',
        'primary-hover': '#003db3',
        'primary-dark': '#001a4e',
        'primary-fixed': '#dbe7fb',
        'primary-fixed-dim': '#a1c2f7',
        // Diamor Gold (from official logo #efcf58)
        secondary: '#c89928',
        'secondary-container': '#fff9e6',
        'secondary-fixed': '#fdeda8',
        'secondary-fixed-dim': '#f7dc7a',
        'tertiary-fixed': '#e2ebf6',
        'gold-shimmer': '#efcf58',
        'gold-accent': '#deb53a',
        'gold-soft': '#fff8e2',
        'silver-accent': '#e2ebf6',
        'deep-navy': '#001642',
        'royal-slate': '#002268',
        'diamor-blue': '#003190',
        'diamor-gold': '#efcf58',
      },
      spacing: {
        'container-max': '1280px',
        'section-padding-desktop': '120px',
        'section-padding-mobile': '64px',
        'gutter': '32px',
      },
      fontFamily: {
        display: ['var(--font-bodoni)', 'serif'],
        body: ['var(--font-opensans)', 'sans-serif'],
      },
      fontSize: {
        'display-lg': ['clamp(38px,6.5vw,64px)', { lineHeight: '1.1', letterSpacing: '-0.02em', fontWeight: '600' }],
        'headline-lg': ['clamp(30px,4.5vw,48px)', { lineHeight: '1.16', fontWeight: '500' }],
        'headline-md': ['32px', { lineHeight: '40px', fontWeight: '500' }],
        'title-lg': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'label-md': ['14px', { lineHeight: '20px', letterSpacing: '0.05em', fontWeight: '600' }],
      },
    },
  },
  plugins: [],
};
